### ISSUE TITLE
Clarify process how project leaders (and deputy project leaders) join the board

### ISSUE THREAD

**Issue by pmai** [modelica/MA-Bylaws#14]
Sentence in section §5 should be clarified, as follows:

> those leaders of registered Modelica Association Projects (see § 21 - § 23) that are approved by the MA assembly.

change to

> the leaders and deputy leaders of registered Modelica Association Projects (see § 21 - § 23) once the respective leader or deputy project leader has been approved by the MA assembly under the rules given in §21 and §16.

A sentence clarifying how the approval is to be handled should be added, e.g. via changing `election` to `election or approval of board members` where applicable. If need be more detail can be added to §16.

**Comment by HansOlsson** [comment]
I think the previous idea was different.

The new text reads as if _they will be approved_ as board members by the MA assembly (almost rubber-stamping them), whereas the previous text suggest that they are not necessarily approved. I believe the previous text should be reformulated (if kept), since I assume the idea isn't that the assembly disapprove of the person leading the project, but only that they think that a board position isn't needed.

For deputies: boards may in Sweden may also elect alternate members ("styrelsesuppleant") - that take over if a member cannot attend (temporarily or permanently), and depending on by-laws they may be allowed to participate in all meetings, but not vote if the non-alternate member participates. On one hand that seems to align with the idea of a deputy, but on the other hand some try to avoid alternate members.

**Comment by chrbertsch** [comment]
Pierre, Hans, Francesco, Christian: 
We propose to go for "alternate members"
